/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 mascot.glb --transform
*/

import { Trail, useGLTF } from '@react-three/drei';
import {editable as e} from '@theatre/r3f'

export function Mascot({material,...props}) {
  const { nodes, materials } = useGLTF('/mascot-transformed.glb')
  return (
//     <Trail
//   width={0.2} // Width of the line
//   color={'hotpink'} // Color of the line
//   length={1} // Length of the line
//   decay={1} // How fast the line fades away
//   local={false} // Wether to use the target's world or local positions
//   stride={0} // Min distance between previous and current point
//   interval={1} // Number of frames to wait before next calculation
//   target={undefined} // Optional target. This object will produce the trail.
//   attenuation={(width) => width*10} // A function to define the width in each point along it.
// >
    <e.group theatreKey='Mascot' {...props} dispose={null}>
      <mesh geometry={nodes.Sphere_1.geometry} material={material? material : materials.Tooth_Mixed_Material_2} position={[0, 2, 0]} rotation={[Math.PI / 2, 0, 0]}/>
    </e.group>
// </Trail>
  )
}

useGLTF.preload('/mascot-transformed.glb');
