/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/FOR_WEB.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_1.geometry}
        material={materials.Tooth_Mixed_Material_2}
        position={[0, 0.115, -0.005]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sweep_4.geometry}
        material={materials.Tooth_Mixed_Material_2}
        position={[0, 0.097, -0.005]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Extrude_remesh.geometry}
        material={materials.Tooth_Mixed_Material_2}
        position={[0, 0.056, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cross_eye_2.geometry}
        material={materials.Tooth_Mixed_Material_2}
        position={[0.01, 0.064, 0.001]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere_3.geometry}
        material={materials.Tooth_Mixed_Material_2}
        position={[-0.01, 0.065, -0.005]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spline_11.geometry}
        material={materials.Tooth_Mixed_Material_2}
        position={[-0.011, 0.043, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spline_3.geometry}
        material={materials.Tooth_Mixed_Material_2}
        position={[0.011, 0.043, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spline_5.geometry}
        material={materials.Tooth_Mixed_Material_2}
        position={[0.005, 0.043, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spline_7.geometry}
        material={materials.Tooth_Mixed_Material_2}
        position={[0, 0.043, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Spline_9.geometry}
        material={materials.Tooth_Mixed_Material_2}
        position={[-0.005, 0.043, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/FOR_WEB.glb");
