/* eslint-disable react/prop-types */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 planet_color.glb --transform
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { editable as e } from "@theatre/r3f";
import * as THREE from 'three';
import gsap from 'gsap';

export function PlanetColor({opacity, mascot}) {
  const { nodes, materials } = useGLTF('/planet_color-transformed.glb');
  const num = -15.946048795792349;

  const hello2 = ()=>{
    materials.Mat.color = new THREE.Color('#888');
  }

  const hello = ()=>{
    materials.Mat.color = new THREE.Color('#fff');
    // if (mascot.current.position.z !== num){
    //   mascot.current.rotation.z = 0;
    // }
    // else{
      gsap.fromTo(mascot.current.rotation,{
        z: mascot.current.rotation.z,
        duration: 0.3,
        ease: 'Power.easeOut'
      },
      {
        z: 0,
        duration: 0.3,
        ease: 'Power.easeOut'
      }
      )
    // }

  }
  
  React.useEffect(()=>{
      materials.Mat.transparent = true;
      materials.Mat.opacity = opacity;
      materials.Mat.color = new THREE.Color('#888');
  },[opacity])
  return (
    <e.group theatreKey='planet_color' dispose={null} onPointerLeave={()=>hello2()} onPointerEnter={()=>hello()} onClick={()=>hello()}>
      <mesh geometry={nodes.Sphere001.geometry} material={materials.Mat} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </e.group>
  )
}

useGLTF.preload('/planet_color-transformed.glb');
